### ISSUE TITLE
Rendering can easily be broken

### ISSUE THREAD

**Issue by Codingale** [thegrb93/StarfallEx#312] opened 2017-10-08 03:51 UTC
A user passed along this code, it breaks the world rendering moving the entire map with it:

    
    --@name
	--@author 
	--@client

	local scale = 80000
	local tex = {
		render.getTextureID(" https://dl.dropboxusercontent.com/u/72472980/cs_tibetft.png "),
		render.getTextureID(" https://dl.dropboxusercontent.com/u/72472980/cs_tibetrt.png "),
		render.getTextureID(" https://dl.dropboxusercontent.com/u/72472980/cs_tibetbk.png "),
		render.getTextureID(" https://dl.dropboxusercontent.com/u/72472980/cs_tibetlf.png "),
		render.getTextureID(" https://dl.dropboxusercontent.com/u/72472980/cs_tibetup.png "),
	}
	local m = {}
	local angles = {
		Angle(0,0,-90),
		Angle(0,90,-90),
		Angle(0,180,-90),
		Angle(0,-90,-90),
		Angle(0,90,0),
		Angle(0,0,180)
	}
	local pos = chip():getPos()+Vector(0,0,scale/6)
	for i=1, 6 do
		m[i] = Matrix()
		m[i]:translate(pos)
		m[i]:rotate(angles[i])
		m[i]:scale(Vector(scale,scale,scale))
		m[i]:translate(Vector(-0.5,-0.5,0.5))
	end

	hook.add("render","",function()
		for i=1, 5 do
			render.pushViewMatrix({type = "3D", zfar = 300000})
			render.pushMatrix(m[i], true)
			render.setTexture(tex[i])
			render.drawTexturedRect(0,0,1,1)
			render.popMatrix()
			render.popViewMatrix()
		end
	end)

**Comment by Codingale** [comment] 2017-10-08 03:53
They also report it's when you use a screen (it seems)

**Comment by thegrb93** [comment] 2017-10-08 04:15
That's a basic example code I posted, but I'll check to be sure.

**Comment by thegrb93** [comment] 2017-10-08 04:16
Yeah, it doesn't break anything and works fine.

**Comment by Codingale** [comment] 2017-10-08 04:26
It appears to break when linked to a screen on our server.. we've narrowed it down to that.. not sure exactly what inside that however causes it. We're running DarkRP.

**Comment by thegrb93** [comment] 2017-10-08 04:35
There must be some addon or gamemode conflict. Can you try it on sandbox and see if it still has that problem? If so then there must be an addon causing it.

**Comment by Codingale** [comment] 2017-10-08 04:37
I'll see.. if so how would we work to figure out which.. side note since there's a lot of people on..

What the hell is the ScrW() and ScrH() functions in Starfall's `render` hook?

**Comment by thegrb93** [comment] 2017-10-08 04:40
?

**Comment by thegrb93** [comment] 2017-10-08 04:40
Where?

**Comment by Codingale** [comment] 2017-10-08 04:46
It's `render.getResolution()` I was a derp and didn't notice that, the auto-complete didn't want to work.

**Comment by Codingale** [comment] 2017-10-09 19:21
Right, so the rendering is broken even after a chanelevel, the world doesn't re-render.
Using Sandbox doesn't break render... though I'm sure some addons could be disabled when changing gamemode..


Any more debugging ideas?

**Comment by thegrb93** [comment] 2017-10-09 19:51
could try disabling all addons, try with darkrp and see if it breaks. Then enable one by one until it breaks.

**Comment by Damianu** [comment] 2017-10-09 20:01
I'd start with non-workshop addons which use render hooks(you can just browse their code with some IDE to find such addons). Then everything related to rendering. Ofc try clear darkrp without any addons first as we dont really test starfall there.

**Comment by Codingale** [comment] 2017-10-22 21:03
Still no idea what's causing it. Seems to be when a screen is linked with DarkRP loaded.. still haven't had a chance to debug it just yet.

**Comment by thegrb93** [comment] 2017-10-22 21:35
I went ahead and ran DarkRP (I really didn't want to) to see if the base gamemode was the cause, and it is. I guess I can try debugging it.

**Comment by thegrb93** [comment] 2017-10-22 21:40
I think it might be this. https://github.com/FPtje/DarkRP/blob/master/gamemode/modules/workarounds/sh_workarounds.lua#L103

**Comment by thegrb93** [comment] 2017-10-27 18:49
Should be fixed in latest version of darkrp.

**Closed by thegrb93** 2017-10-27 18:49 UTC
Labels: 3rd party bug

**Comment by Codingale** [comment] 2017-10-28 05:09
Yep, it's fixed now tested and it causes no issues.
