### ISSUE TITLE
Code updating and holograms bug.

### ISSUE THREAD

**Issue by Damianu** [thegrb93/StarfallEx#104] opened 2017-01-13 20:02 UTC
If you update code having some holograms, it wont clean up them before starting new code, so after update you get error about hologram limit. Workaround is to update 2 times.

**Comment by thegrb93** [comment] 2017-01-14 00:54
I think the problem is the previous instance is deinitializing after the new one initializes so I'll fix that.

**Comment by thegrb93** [comment] 2017-01-14 01:15
Should be fixed, but let me know if it still happens.

**Closed by thegrb93** 2017-01-14 01:15 UTC
Labels: bug
