### ISSUE TITLE
Lua error on the Chromium branch

### ISSUE THREAD

**Issue by dvdvideo1234** [thegrb93/StarfallEx#1311] opened 2022-04-28 18:43 UTC
```
SERVER

[starfallex] [SF] Attempt to load bad module: starfall/libs_sv/stargate.lua
starfall/libs_sv/stargate.lua:6: assertion failed!
stack traceback:
            [C]: in function 'assert'
            starfall/libs_sv/stargate.lua:6: in function 'r'
            addons/starfallex/lua/starfall/sflib.lua:1786: in function <addons/starfallex/lua/starfall/sflib.lua:1786>
            [C]: in function 'xpcall'
            addons/starfallex/lua/starfall/sflib.lua:1786: in function 'compileModule'
            addons/starfallex/lua/starfall/sflib.lua:1800: in function 'addModule'
            addons/starfallex/lua/starfall/sflib.lua:1816: in function 'loadModules'
            addons/starfallex/lua/starfall/sflib.lua:1821: in main chunk
            [C]: in function 'include'
            addons/starfallex/lua/autorun/server/sf_init.lua:34: in main chunk

    1. compileModule - addons/starfallex/lua/starfall/sflib.lua:1788
        2. addModule - addons/starfallex/lua/starfall/sflib.lua:1800
            3. loadModules - addons/starfallex/lua/starfall/sflib.lua:1816
                4. unknown - addons/starfallex/lua/starfall/sflib.lua:1821
                    5. include - [C]:-1
                        6. unknown - addons/starfallex/lua/autorun/server/sf_init.lua:34

CLIENT

[starfallex] Failed to read whitelist file!
    1. Require - addons/starfallex/lua/starfall/sflib.lua:861
        2. r - addons/starfallex/lua/starfall/libs_cl/socket.lua:1
            3. unknown - addons/starfallex/lua/starfall/sflib.lua:1786
                4. xpcall - [C]:-1
                    5. compileModule - addons/starfallex/lua/starfall/sflib.lua:1786
                        6. addModule - addons/starfallex/lua/starfall/sflib.lua:1804
                            7. loadModules - addons/starfallex/lua/starfall/sflib.lua:1816
                                8. unknown - addons/starfallex/lua/starfall/sflib.lua:1822
                                    9. include - [C]:-1
                                        10. unknown - addons/starfallex/lua/autorun/client/sf_init.lua:8
```

**Comment by x4fx77x4f** [comment] 2022-04-28 18:55
Server error: Duplicate of #1196. `starfall/libs_sv/stargate.lua` doesn't exist in StarfallEx. This error is from [The Stargate Carter Pack](https://github.com/RafaelDeJongh/cap). It's supposed to silently fail on newer versions of Starfall, but it wasn't expecting `SF.Entities` to have been removed. Make an issue there.
Client error: Duplicate of #1264. The version of the socket module included in the repository will throw an error if it can't read its whitelist file.

**Closed** 2022-04-28 19:58 UTC
Labels: not a bug
