### ISSUE TITLE
Permissions working but not showing in editor

### ISSUE THREAD

**Issue by OrIOg** [thegrb93/StarfallEx#343] opened 2017-12-16 13:53 UTC
The permissions are working fine, but each time I reopen the menu and go in the tab permission they are all off. I know it's just a graphical issue but that's quite annoying.

**Comment by Damianu** [comment] 2017-12-16 14:48
Do you have any errors?
Also does same apply for rightclick chip in context mode > starfallex > open global permissions ?

**Comment by OrIOg** [comment] 2017-12-16 18:14
No error :/ And yes it's same with "open global permissions"

**Comment by Damianu** [comment] 2017-12-16 18:57
Are you sure you are using latest starfall version? I cant reproduce that.

**Comment by Damianu** [comment] 2017-12-16 18:58
Oh, it happens only for clientside permissions.

**Comment by Damianu** [comment] 2017-12-16 19:01
@thegrb93 lua_run_cl PrintTable(SF.Permissions.providers["client"]) seems to miss "settings" where previously permissions were stored. Where are they now?

**Comment by Damianu** [comment] 2017-12-16 19:16
It's fixed, however I am not sure if clientside providers lacking settings table was intended so I'll leave this open for now.

**Comment by thegrb93** [comment] 2017-12-16 20:47
its in SF.Permissions.privileges.<privilage>[3].settings

**Comment by Damianu** [comment] 2017-12-16 20:58
Already found that and made UI look for those instead, if this was planned we may close it then.

**Comment by thegrb93** [comment] 2017-12-16 22:34
ok good. thx

**Closed by thegrb93** 2017-12-16 22:34 UTC
