### ISSUE TITLE
Attempt to call `AddHook` a nil value

### ISSUE THREAD

**Issue by dvdvideo1234** [thegrb93/StarfallEx#962] opened 2020-09-20 20:10 UTC
Hello, the last version of starfall cloned from the repo.

The error stack:
```
starfall/libs_sv/acffunctions.lua:63: attempt to call field 'AddHook' (a nil value)
stack traceback:
	starfall/libs_sv/acffunctions.lua:63: in main chunk
	[C]: in function 'xpcall'
	addons/starfallex/lua/starfall/sflib.lua:1363: in function 'compileModule'
	addons/starfallex/lua/starfall/sflib.lua:1382: in function 'addModule'
	addons/starfallex/lua/starfall/sflib.lua:1399: in function 'loadModules'
	addons/starfallex/lua/starfall/sflib.lua:1404: in main chunk
	[C]: in function 'include'
	addons/starfallex/lua/autorun/server/sf_init.lua:84: in main chunk
```

**Comment by adamnejm** [comment] 2020-09-20 20:22
Duplicate of https://github.com/thegrb93/StarfallEx/issues/872

That's Starfall extension, not Starfall itself.
It will happen until maintainers of ACF merge this:  
https://github.com/nrlulz/ACF/pull/331
  
Afaik ACF is no longer maintained and long forgotten by the devs, so I see no harm in switching to this:  
https://github.com/DaDamRival/ACF/tree/starfall_fix  
It's ACF with fixes for Starfall. You shouldn't notice any differences as it's ahead ACF's master branch.  
  
Or just use [ACF-3](https://github.com/Stooberton/ACF-3)

**Closed** 2020-09-20 20:42 UTC

**Comment by dvdvideo1234** [comment] 2020-09-21 18:41
Thank you very much !
