### ISSUE TITLE
Request for a key locking function or something similar for displays.

### ISSUE THREAD

**Issue by zxvnm4** [thegrb93/StarfallEx#666] opened 2019-08-31 03:47 UTC
Having a way to control what keyboard and mouse inputs get passed on to the game might be a little too powerful by itself. Given how this project has a way to prevent camera rotation and allow the mouse to move freely for the hud component, I can wager having a way to allow the user to write without activating various keybinds isn't super bad? You could limit it by some hard coded key that the wire keyboard uses, and make it only work if permissions exist, if you are using a hud or if you are pressing e on a screen. 

Implementation could just be as simple as making the screen act exactly as the wire keyboard does, you can just disable and enable that feature.(aka using the screen will lock controls until you press alt, and you have a small prompt in chat or onscreen that tells you what key will unlock the controls.) After all doing something like that would make it just abusable as the wire keyboard, and given how that already exists I can't see why adding this wouldn't hurt.

Or you could make it a permission that's set default is to not allow it, but once given permission the chip can do it anytime, or maybe just anytime a hud is active or you are looking at a screen.\

There really isn't any way to do this and it would allow me to have my gui program not have to use a on screen keyboard. Oh cool this is issue number 666, how... ominous.

**Comment by thegrb93** [comment] 2019-08-31 07:16
Duplicate of https://github.com/thegrb93/StarfallEx/issues/494 I think

**Comment by zxvnm4** [comment] 2019-08-31 07:23
The title for #494 is sorta vague, I should also note some of the things I've said in the description on how to implement this feature. I would greatly appreciate it.

**Comment by zxvnm4** [comment] 2019-08-31 19:41
Hm, I've updated what I said earlier, I was being too critical.

**Comment by zxvnm4** [comment] 2019-09-02 06:20
I'm a little curious as to why you didn't add a feature to allow the screen component to also act as a keyboard too? Hmm, but the way I described it probably wasn't specific enough so I'll describe it 
better here. 
Having a global inputlock is very abusable, but having this feature just for the hud does not help me make a search bar for my screen work seamlessly, so I think having a function which will make the screen itself act like the keyboard entity would be great. The implementation could as simple as when the screen entity is 'used' and 'inputlockkeyboard' variable is enabled the user will have their controls locked. The key that exits you out of the keylocking and the 10 second wait time should, of course, be also included. 
This makes it just like an toggleable wirekeyboard, the screen should just act exactly like that entity, except you can also display stuff on it.

I hope this isn't so much for you? I would greatly appreciate something like this for my gui api that I made for funzies.

**Comment by thegrb93** [comment] 2019-09-02 08:35
I think a way to allow screens to also lock controls would be a good feature.

**Closed** 2019-09-14 04:14 UTC
Labels: duplicate
